name: Deployment

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    environment:
      name: prod
      url: https://prod.example.com

    steps:
    - uses: actions/checkout@v2

    - name: Run Tests
      run: echo ${{ secrets.FORGE_DEPLOYMENT_URL }}

