name: Deployment

on: [repository_dispatch, workflow_dispatch]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Test Suite
      run: echo "work work"


  # Deploy app to Staging Environment
  deploy_stag:
    runs-on: ubuntu-latest
    needs: [test] # deployment will only run if tests pass

    environment:
      name: stag
      url: https://stag.example.com #

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to stag
      run: curl ${{ secrets.FORGE_DEPLOYMENT_URL }}


  # Deploy app to Production Environment
  deploy_prod:
    runs-on: ubuntu-latest
    needs: [test] # deployment will only run if tests pass

    environment:
      name: prod
      url: https://prod.example.com

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to prod
      run: curl ${{ secrets.FORGE_DEPLOYMENT_URL }}

