name: Deployment

on: repository_dispatch

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Test Suite
      run: echo "run test suite"

  deploy_stag:
    runs-on: ubuntu-latest
    needs: [test]

    environment:
      name: stag
      url: https://stag.example.com

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to stag
      run: echo "use ${{ secrets.FORGE_DEPLOYMENT_URL }}"


  deploy_prod:
    runs-on: ubuntu-latest
    needs: [test]

    environment:
      name: prod
      url: https://prod.example.com

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to production
      run: echo "use ${{ secrets.FORGE_DEPLOYMENT_URL }}"

